/**
 * Created by Frimko on 20.10.2017.
 * mailto ccc-car@yandex.ru.
 */

export const FETCH_REQUEST_FAILURE = 'FETCH_REQUEST_FAILURE';


export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const SELECT_CUSTOMERS = 'SELECT_CUSTOMERS';
export const SELECT_CUSTOMERS_SUCCESS = 'SELECT_CUSTOMERS_SUCCESS';
export const SELECT_CUSTOMERS_FAILURE = 'SELECT_CUSTOMERS_FAILURE';



export const CUSTOMERS_FETCH_REQUEST_SUCCESS = 'CUSTOMERS_FETCH_REQUEST_SUCCESS';

export const SHOW_CUSTOMERS_MODAL = 'SHOW_CUSTOMERS_MODAL';
export const HIDE_CUSTOMERS_MODAL = 'HIDE_CUSTOMERS_MODAL';

export const PRODUCTS_FETCH_REQUEST_SUCCESS = 'PRODUCTS_FETCH_REQUEST_SUCCESS';

export const SHOW_PRODUCTS_MODAL = 'SHOW_PRODUCTS_MODAL';
export const HIDE_PRODUCTS_MODAL = 'HIDE_PRODUCTS_MODAL';
